version: '3.8'

services:
  postgres_db:
    image: postgres:15-alpine
    container_name: reservation_postgres
    environment:
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-password123}
      POSTGRES_DB: ${DB_NAME:-reservation_db}
    ports:
      - "5430:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  api:
    build: .
    container_name: reservation_api
    ports:
      - "9090:9090"
    depends_on:
      - postgres_db
    environment:
      DB_HOST: postgres_db 
      DB_USER: ${DB_USER:-postgres}
      DB_PASSWORD: ${DB_PASSWORD:-password123}
      DB_NAME: ${DB_NAME:-reservation_db}
      DB_PORT: 5432

volumes:
  pgdata: