name: "push_pr"

on:
  push:
    branches:
      - main
      - "adjust-project"
  pull_request:
    branches:
      - "adjust-project"
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - name: "Checkout code"
        uses: actions/checkout@v4

      - name: "Run tests"
        run: npm test

